# Generated by Django 4.1.7 on 2023-04-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobBoardAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=30)),
                ('job_description', models.TextField()),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('create_at', models.DateField()),
                ('avabile', models.BooleanField(default=True)),
            ],
        ),
       
    ]
